server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: websocket
              uri: http://localhost:8081
              predicates:
                - Path=/websocket/**
              filters:
                - StripPrefix=1
            - id: payment-service
              uri: http://localhost:8082
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1
            - id: inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=/inventory/**
              filters:
                - StripPrefix=1
            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/orders/**
              filters:
                - StripPrefix=1
            - id: user-service
              uri: http://localhost:8085
              predicates:
                - Path=/cms/auth/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
